# Site settings
title: plasticpencil
email: plasticpencil@cyetain.com
description: > # this means to ignore newlines until "baseurl:"
  I’m going to put book reviews,pictures and questions for you
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://foxnerd.rocks” # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  foxnerd

# Build settings
markdown: kramdown
